package AutoSpace.Types;

public enum ResearchType {

	ESPIONAGE_TECHNOLOGY("106"), COMPUTER_TECHNOLOGY("108"), WEAPON_TECHNOLOGY("109"), SHIELDING_TECHNOLOGY(
			"110"), ARMOUR_TECHNOLOGY("111"), ENERGY_TECHNOLOGY("113"), HYPERSPACE_TECHNOLOGY("114"), COMBUSTION_DRIVE(
					"115"), IMPULSE_DRIVE("117"), HYPERSPACE_DRIVE("118"), LASER_TECHNOLOGY("120"), ION_TECHNOLOGY(
							"121"), PLASMA_TECHNOLOGY("122"), INTERGALACTIC_RESEARCH_NETWORK(
									"123"), ASTROPHYSICS("124"), GRAVITON_TECHNOLOGY("199");

	private String id;

	ResearchType(String id) {
		this.id = id;
	}

	public String id() {
		return id;
	}
}
